import type { Metadata } from "next";
import { Poppins } from 'next/font/google';
import "./globals.css";
import Footer from "./components/atoms/Footer";
import NavBar from "./components/atoms/NavBar";

/*const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
*/
const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '700'], // Add the weights you need
});

export const metadata: Metadata = {
  title: "Salma's First Next Try",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={poppins.className}
      >
        <NavBar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
